### ISSUE TITLE
Alternative mechanism required for resources with illegal python names

### ISSUE THREAD

**Issue by aalcock** [datafolklabs/drest#10]
Many REST resources are on URL's with tildes, hyphens or other 'weird' characters (eg see https://developer.linkedin.com/documents/groups-api)

In drest, the resource is accessed as though it were an attribute of the API instance, eg:

``` python
api.my.path.to.resource.get()

# broken when trying linkedin:
api.~.group-memberships
      ^
SyntaxError: invalid syntax
```

Clearly this cannot be solved - that would modify the lexer in Python. However there needs to be an alternative way for accessing the resources, for example using the dict pattern:

``` python
api['~']['group-memberships']
```

**Comment by derks** [comment]
Yeah, we definitely need to handle special characters.  Would it be possible to get a full code snippit of how your setting the api up to talk to LinkedIn?  They seem to have quite a different api design than just a straight REST url structure.  One thing to note is that you can specify the name (what is appended to the api object) as well as the path:

<pre>
api.add_resource('group_memberships', path='/people/~/group-memberships')
api.group_memberships.get()
</pre>


Maybe that will work?

**Comment by derks** [comment]
In my last commit I've added a check that resource names can not contain non alpha-numeric characters (other than '_' and '.'):

https://github.com/derks/drest/commit/6117026f1fdeed7804830f419afe74a06a588abf#L3R241

This doesn't exactly resolve this issue, but helps prevent unexpected tracebacks.

**Comment by derks** [comment]
Any feedback on the above, or can I close this out?

**Comment by aalcock** [comment]
Hi BJ

Sorry but I am very focused on another product right now and I cannot validate if this change fixes the problem without re-integrating the new library.

Please feel free to close it. I will reopen or reraise if I get further problems

Sorry to take so long in answering.

Rgds

```
Andrew
```
