### ISSUE TITLE
Why don't you use setup.py at top directory?

### ISSUE THREAD

**Issue by yrik** [datafolklabs/drest#14]
I want to install drest via pip from this repo and there are no option to do it.

**Comment by derks** [comment]
I've been considering this issue lately.  For this project, having python packages unser 'src/' isn't that important as it is a small code base.  However I have other projects that more so require it, such as http://github.com/derks/cement where extensions are broken out into their own packages... and I don't want to maintain seperate git repos or have a confusing source tree.

The ideal solution would be for pip to support a '--setup-prefix'.  To that, I've submitted a feature request:

https://github.com/pypa/pip/issues/572

I'll give that some time to see what feedback the PIP developers have... and if they reject the request then I will consider altering the source tree.

Thanks.

**Comment by derks** [comment]
Apprently PIP will support this functionality in the near future:

https://github.com/pypa/pip/pull/526

**Comment by yrik** [comment]
Wow, nice!

10 июня 2012, в 00:29, BJ Dierkes написал(а):

**Comment by derks** [comment]
This is resolved, you can now do the following:

<pre>
pip install -e git+git://github.com/derks/drest.git#egg=drest
</pre>
