### ISSUE TITLE
Can't use TastyPieAPI

### ISSUE THREAD

**Issue by bclermont** [datafolklabs/drest#27]
```
Traceback (most recent call last):
  File "a.py", line 2, in <module>
    api = drest.api.TastyPieAPI('http://localhost:8000/api/v1/', auth_mech='basic')
  File "/Users/ben/sandbox/salt/inventory/env/src/drest/drest/api.py", line 385, in __init__
    self.find_resources()
  File "/Users/ben/sandbox/salt/inventory/env/src/drest/drest/api.py", line 433, in find_resources
    self.add_resource(resource)
  File "/Users/ben/sandbox/salt/inventory/env/src/drest/drest/api.py", line 250, in add_resource
    "resource name must be alpha-numeric."
drest.exc.dRestResourceError: resource name must be alpha-numeric.
```

it raise exception **before** I can get an instance.
so, I can't use api.auth()

**Comment by oliverdrake** [comment]
Are you also developing the API that you're querying? If so, are you not using alphanumeric characters intentionally? Assuming it's not just something weird happening with your tastypie setup, you could turn off resource discovery and manually add the resources you're interested in:

``` python
class MyAPI(TastypieAPI):
    class Meta:
        request_handler = request.TastyPieRequestHandler
        resource_handler = resource.TastyPieResourceHandler
        auto_detect_resources = False
        auth_mech = 'basic'

api = MyAPI('http://localhost:8000/api/v1/')
api.add_resource('resource_name')
api.resource_name.get(1)
```

As a temporary workaround, hope this helps

**Comment by derks** [comment]
@bclermont Can you provide some more context?  Perhaps the API class your are defining.  You might also get more info if you enable debugging in your terminal session:

```
$ export DREST_DEBUG=1
```

Any API calls made by drest will get printed to console, which may or may not be helpful to narrow down the issue.
