### ISSUE TITLE
Examples of API Clients created using drest?

### ISSUE THREAD

**Issue by CT83** [datafolklabs/drest#36]
I remember seeing a list of Python Clients and sample projects which were using drest, somewhere around here. 
I am thinking about creating my own Client and would like some examples of how others have done it. Could you please point me to some?

**Comment by derks** [comment]
@CT83 I don't have any working examples ready, however my general approach to building API clients is to setup the client object in a `post_argument_parsing` hook, and then extend the app object with it.

For example (please note this is psuedo code):

```python
from cement import App

def extend_my_api_client(app):
    # get connection details from app config
    api_host = app.config.get('myapp', 'api_host')
    api_token = app.config.get('myapp', 'api_token')

    # setup the api client object
    my_api_client = SomeAPIClientClass(base_url=api_host)
 
    # setup authentication with the api
    my_api_client.auth(token=api_token)

    # extend the object onto the app
    app.extend('api', my_api_client)


class MyApp(App):
    class Meta:
        label = 'myapp'
        hooks = [
            ('post_argument_parsing', extend_my_api_client),
        ]
```


From there, you can access `app.api.whatever()` throughout your app and plugins.  Does that help?

**Comment by CT83** [comment]
Hmm, Yes! This helps. So I guess.
https://drest.readthedocs.io/en/latest/customization.html Would help me too.
I had not thought of using a single API instance for the entire Server, I
think I will use your general idea for some of my other projects too, it
seems cleaner.

**Comment by derks** [comment]
@CT83 in the case of drest, you'd generally have a single api object and then add/define resources on it.  You'd end up with `app.api.users.get()`, `app.api.projects.get(1234)`, etc.

 - https://github.com/datafolklabs/drest#usage

**Comment by CT83** [comment]
Ah! Got it! Thanks. This has been really helpful.

**Comment by CT83** [comment]
(Feel free to close this)

**Comment by derks** [comment]
I apologize...  I was confused earlier thinking this thread was in another project (Cement).  The above examples and context make no sense...  I’m really sorry to confuse you.

The documentation is pretty straight forward but I’d be happy to help wherever you need it.  If the api is REST-like, it’s pretty much a matter of adding your resources and using the builtins.  If there is a specific api let me know and I can look into it with you.

**Comment by CT83** [comment]
Ah, that explains it, don't worry about it. I was just looking for some
examples of APIs using drest. We are currently making something for
internal use, I just wanted to see if there were any open source projects
using drest.
