### ISSUE TITLE
Add capability to suppress final forward-slash

### ISSUE THREAD

**Issue by aalcock** [datafolklabs/drest#6]
Currently drest forces all Resource URLs to end with a forward slash (RequestHandler.request() creates the URL using a string format "%s%s/").

Some REST services have Resources at URIs ending with a slash, and some emphatically require no final slash. The above behaviour therefore makes drest incompatible with many REST services.

I would propose something along the lines of setting a flag either on the API itself, or possibly also at Resource level, (let's call this "append_slash") to disable this builtin behaviour. Default behaviour could be to set this true and so preserve current behaviour. Then the following can be implemented:

``` python
class RequestHandler(MetaMixin):
    # ...snip...
    def request(self, method, path, params={}, headers={}):
        # ...snip...
        if path == '':
            url = self._meta.baseurl
        else:
            url = "%s%s%s" % (self._meta.baseurl, path, "/" if self._meta.append_slash else "")
```

**Comment by derks** [comment]
This is already committed in master.
