### ISSUE TITLE
Add ability to add extra url parameters to a Resource

### ISSUE THREAD

**Issue by aalcock** [datafolklabs/drest#8]
This is a similar request to #5, but instead of being able to call add_header, we should be able to call add_url_param as well. This would add "permanent" parameters to a Resource, sent with every request.

This is currently implemented on the RequestHandler with the add_url_param method saving the results in the _extra_url_params slot.

It's probable that, if #5 is resolved by exposing the Request object, then this will be automatically solved.

**Comment by derks** [comment]
The request object will be public in the next release.
